# Generated by Django 5.1.3 on 2024-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(default='Bkash', max_length=100),
            preserve_default=False,
        ),
    ]
